### ISSUE TITLE
alexa-skill-tester writes object instead of json string as response?

### ISSUE THREAD

**Issue by alexa-bIT** [pmarkert/lambda-testing-framework#1]
Hi Phillip,

thanks for this great testing tool!

I got an error wiriting the response file. 
If response file does not yet exist, currently the response object is written as [object object] to the response file.

May be in index.js at line 40 there is an error?
fs.writeFileSync(response_filename, response);
 
Should be changed to: 
fs.writeFileSync(response_filename, JSON.stringify(response));

Thanks in advance, 
alexa-bIT

**Comment by pmarkert** [comment]
Hi there, thanks for your feedback. I believe that you are using a very old version (1.1.2 perhaps?). This has been fixed in the following version (2.0.0). I could potentially make a 1.x patch for you, but there have been some good improvements since 1.x. including promises and pre/post validation hooks.

**Comment by leighgraner** [comment]
Hi, https://www.npmjs.com/package/alexa-skill-tester claims that 1.1.2 is the latest release of alexa-skill-test. I found this convo because I have the same issue.

**Comment by alexa-bIT** [comment]
hi, 
in deed, I had an old version: alexa-skill-tester (1.1.2). 
I successfully switched to "lambda-testing-framework (3.1.0) and now it works!
Thanks for your help,
alexa-bIT
