### ISSUE TITLE
equals regex in responses

### ISSUE THREAD

**Issue by fingejo** [pmarkert/lambda-testing-framework#2]
I managed to install the library and to run several tests successfully. But in my Code I do different API calls that return live Data. So in my responses I have to somehow validate the syntax but not the exact values. What is the best way to do this? I think there are some implemented methods in Chai but I dont really want to dig into the library. What is the best way to do this?

**Comment by pmarkert** [comment]
Hi there. This library is primarily intended to be used for unit-testing, as opposed to integration testing. With unit tests, the response is often well-defined and usually not dynamic. In my own experience, many times the back-end services that provide dynamic data are stubbed out or mocked so as not to interfere with the "component under test". However, I like your idea for making the response assertions more powerful to allow for some better flexibility. The challenge is finding a way to express those with files instead of in code. Or perhaps allowing a .js based validation function to check response. If you have time to contribute and a recommendation for how you think this could work, I'd love to discuss and perhaps collaborate on a pull request, but otherwise I do not have a lot of time to spend at the moment on maintaining/improving this library beyond the specific needs for which it already serves.

**Comment by fingejo** [comment]
Thank you for your quick response.
The answer was already there: in the index.js of your library there is a possibility for a regex pattern file. So you can validate your responses either vs a json or a regex pattern. That's all I was searching for (:
(The code I pulled from npm and used for this looks a bit different though)
